const leads=[
 {name:'Maya Chen',initials:'MC',role:'VP, Revenue Operations',company:'Lumen Health',score:96,stage:'Qualified',source:'Website demo request',intent:'High',owner:'Priya Shah',territory:'North America',timeline:['Demo requested via website form','Enriched through Clearbit mock','ICP score calculated: 96/100','Assigned to Priya based on NA enterprise rule']},
 {name:'Jordan Blake',initials:'JB',role:'Head of Growth',company:'Orbitly',score:91,stage:'Meeting booked',source:'Cold email reply',intent:'High',owner:'Marcus Lee',territory:'EMEA',timeline:['Replied positively to outbound sequence','Reply webhook deduplicated by email','Meeting booked through Calendly mock','Opportunity created in pipeline']},
 {name:'Sofia Patel',initials:'SP',role:'Director of Sales',company:'NexaCloud',score:87,stage:'Qualified',source:'LinkedIn outreach',intent:'High',owner:'Priya Shah',territory:'North America',timeline:['Imported from LinkedIn outreach','Viewed pricing page twice','Fit score changed from 68 to 87','Assigned to Priya']},
 {name:'Ethan Ross',initials:'ER',role:'Founder & CEO',company:'Tandem AI',score:76,stage:'Nurturing',source:'Partner referral',intent:'Medium',owner:'Marcus Lee',territory:'North America',timeline:['Partner referral submitted','Company enriched','Entered founder nurture sequence']},
 {name:'Amara Okafor',initials:'AO',role:'Operations Lead',company:'Brightpath',score:68,stage:'Needs action',source:'CSV import',intent:'Medium',owner:'Unassigned',territory:'EMEA',timeline:['CSV batch imported','Duplicate check passed','Awaiting territory assignment']}
];
const activity=[['↳','Maya Chen','submitted a demo request','2m'],['✉','Jordan Blake','replied to Sequence: EMEA leaders','12m'],['◫','Sofia Patel','moved to Qualified','24m'],['◷','System','routed 6 new leads to owners','41m'],['◉','Ethan Ross','was referred by Acme Partners','1h']];
let selected=leads[0]; let filter='all';
const $=s=>document.querySelector(s);
function scoreClass(n){return n>=85?'high':n>=70?'mid':'low'}
function renderLeads(){const list=$('#leadList');let shown=leads.filter(l=>filter==='all'||filter==='needs'&&l.stage==='Needs action'||filter==='hot'&&l.intent==='High');list.innerHTML=shown.map((l,i)=>`<article class="lead-row" data-index="${leads.indexOf(l)}"><span class="lead-avatar">${l.initials}</span><span><span class="lead-name">${l.name}</span><span class="lead-role">${l.role}</span></span><span class="company">${l.company}</span><span class="score ${scoreClass(l.score)}">${l.score} score</span><span class="lead-arrow">›</span></article>`).join('');document.querySelectorAll('.lead-row').forEach(el=>el.addEventListener('click',()=>openLead(leads[el.dataset.index])))}
function renderActivity(){ $('#activityList').innerHTML=activity.map(e=>`<div class="event"><span class="event-icon">${e[0]}</span><p><b>${e[1]}</b> ${e[2]}</p><time>${e[3]}</time></div>`).join('') }
function openLead(lead){selected=lead;$('#dialogContent').innerHTML=`<h2>${lead.name}</h2><p class="dialog-company">${lead.role} at ${lead.company}</p><div class="detail-grid"><div>Lead score<b>${lead.score} / 100</b></div><div>Stage<b>${lead.stage}</b></div><div>Source<b>${lead.source}</b></div><div>Owner<b>${lead.owner}</b></div></div><div class="timeline">${lead.timeline.map(x=>`<p>${x}</p>`).join('')}</div>`;$('#leadDialog').showModal()}
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{filter=btn.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===btn));renderLeads()}));
$('#advanceLead').addEventListener('click',e=>{e.preventDefault();const next={"Needs action":"Qualified",Qualified:"Sequence enrolled",Nurturing:"Qualified","Meeting booked":"Opportunity created"};const stage=next[selected.stage]||'Closed won';selected.stage=stage;selected.timeline.unshift(`Stage advanced to ${stage}`);$('#leadDialog').close();showToast(`${selected.name} advanced to ${stage}`);renderLeads()});
$('#newLead').addEventListener('click',()=>showToast('Lead capture endpoint is ready for a new intake.'));
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2700)}renderLeads();renderActivity();
