import { FormEvent, ReactNode, useEffect, useMemo, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import { QueryClient, QueryClientProvider, useQuery } from "@tanstack/react-query";
import { BrowserRouter, Link, Navigate, Route, Routes } from "react-router-dom";
import { api, restoreCsrfFromCookie, Session, setCsrf } from "./api";
import { EmptyState, PageHeader, Skeleton, Status, label } from "./components/ui";
import { JobsView } from "./features/jobs/JobsView";
import { CampaignsView, CampaignWorkspace } from "./features/campaigns/CampaignsView";
import { IntegrationsView } from "./features/gmail/IntegrationsView";
import "./styles.css";

const client = new QueryClient();
const navItems = [["/", "Home"], ["/prospects", "Prospects"], ["/campaigns", "Campaigns"], ["/inbox", "Inbox"], ["/settings", "Settings"]] as const;

function Login({ onSession }: { onSession: (session: Session) => void }) {
  const [email, setEmail] = useState("admin@signalflow.local"); const [password, setPassword] = useState("change-me-local-password"); const [error, setError] = useState("");
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); try { const result = await api.login(email, password); setCsrf(result.csrf_token); onSession(await api.session()); } catch (caught) { setError(caught instanceof Error ? caught.message : "Sign-in failed"); } };
  return <main className="login-page"><section><span className="brand">SignalFlow</span><h1>Outbound operations, with evidence.</h1><p>Local qualification, mandatory Ollama analysis, controlled Gmail delivery, and a complete audit trail.</p><form onSubmit={submit}><label>Workspace email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label>{error && <p className="inline-error">{error}</p>}<button>Sign in</button></form></section></main>;
}

function AppShell({ session }: { session: Session }) {
  const [workspaceId, setWorkspaceId] = useState(session.workspaces[0]?.id || ""); const workspace = session.workspaces.find((item) => item.id === workspaceId); const jobs = useQuery({ queryKey: ["jobs-indicator", workspaceId], queryFn: () => api.jobs(workspaceId), refetchInterval: 4000 }); const active = jobs.data?.filter((job) => ["queued", "running", "retrying"].includes(job.status)).length || 0;
  return <div className="console-shell"><aside className="console-nav"><Link to="/" className="brand">SignalFlow</Link><p className="nav-caption">Campaign operations</p><nav>{navItems.map(([to, name]) => <Link to={to} key={to}>{name}</Link>)}</nav><div className="nav-footer"><label>Workspace<select value={workspaceId} onChange={(event) => setWorkspaceId(event.target.value)}>{session.workspaces.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><p>{session.user.email}</p></div></aside><main className="console-main"><header className="console-topbar"><div><strong>{workspace?.name || "Workspace"}</strong><span>Prepare, review, launch</span></div><Link to="/settings" className="jobs-pill">{active ? `${active} preparing` : "All systems idle"}</Link></header><Routes><Route path="/" element={<Overview workspaceId={workspaceId} />} /><Route path="/prospects" element={<Prospects workspaceId={workspaceId} />} /><Route path="/campaigns" element={<CampaignsView workspaceId={workspaceId} />} /><Route path="/campaigns/:campaignId" element={<CampaignWorkspace workspaceId={workspaceId} />} /><Route path="/inbox" element={<Outreach workspaceId={workspaceId} />} /><Route path="/settings" element={<Settings workspaceId={workspaceId} />} /><Route path="/accounts" element={<Navigate to="/prospects" replace />} /><Route path="/leads" element={<Navigate to="/prospects" replace />} /><Route path="/outreach" element={<Navigate to="/inbox" replace />} /><Route path="/jobs" element={<Navigate to="/settings" replace />} /><Route path="/imports" element={<Navigate to="/campaigns" replace />} /><Route path="/integrations" element={<Navigate to="/settings" replace />} /><Route path="/templates" element={<Navigate to="/settings" replace />} /><Route path="/audit" element={<Navigate to="/settings" replace />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></main></div>;
}

function Overview({ workspaceId }: { workspaceId: string }) {
  const analytics = useQuery({ queryKey: ["analytics", workspaceId], queryFn: () => api.analytics(workspaceId), refetchInterval: 5000 }); const campaigns = useQuery({ queryKey: ["overview-campaigns", workspaceId], queryFn: () => api.campaigns(workspaceId) }); const jobs = useQuery({ queryKey: ["overview-jobs", workspaceId], queryFn: () => api.jobs(workspaceId), refetchInterval: 3000 });
  const metrics = useMemo(() => [{ label: "Qualified leads", value: analytics.data?.qualified || 0 }, { label: "Campaign ready", value: analytics.data?.campaign_ready || 0 }, { label: "Messages sent", value: analytics.data?.sent || 0 }, { label: "Replies", value: analytics.data?.replied || 0 }], [analytics.data]);
  return <section><PageHeader title="Start your next campaign" description="Upload prospects, let SignalFlow prepare them, review AI-written outreach, then launch with safeguards." actions={<Link className="button" to="/campaigns">Create campaign</Link>} /><div className="signal-strip">{metrics.map((metric) => <div key={metric.label}><strong>{metric.value}</strong><span>{metric.label}</span></div>)}</div><div className="overview-grid"><article className="panel"><h3>Preparing now</h3>{jobs.isLoading ? <Skeleton /> : jobs.data?.filter((job) => ["queued", "running", "retrying"].includes(job.status)).slice(0, 4).map((job) => <div className="compact-row" key={job.id}><div><strong>{job.name}</strong><span>{label(job.phase)}</span></div><Status value={job.status} /></div>) || <EmptyState title="Nothing is processing" body="Campaign imports and AI research appear here while they run." />}</article><article className="panel"><h3>Active campaigns</h3>{campaigns.data?.length ? campaigns.data.slice(0, 4).map((campaign) => <Link className="compact-row" to={`/campaigns/${campaign.id}`} key={campaign.id}><div><strong>{campaign.name}</strong><span>{campaign.enrollment_total} enrolled</span></div><Status value={campaign.status} /></Link>) : <EmptyState title="No campaign created" body="Create a draft and upload your list inside it." action={<Link to="/campaigns">Create campaign</Link>} />}</article></div></section>;
}

function Prospects({ workspaceId }: { workspaceId: string }) { const accounts = useQuery({ queryKey: ["accounts", workspaceId], queryFn: () => api.companies(workspaceId) }); const leads = useQuery({ queryKey: ["leads", workspaceId], queryFn: () => api.leads(workspaceId) }); const [tab, setTab] = useState<"accounts" | "contacts">("accounts"); const records = tab === "accounts" ? accounts.data : leads.data; return <section><PageHeader title="Prospects" description="Your reusable account and contact library. Campaign uploads automatically add and prepare records here." /><div className="segmented"><button className={tab === "accounts" ? "active" : ""} onClick={() => setTab("accounts")}>Accounts</button><button className={tab === "contacts" ? "active" : ""} onClick={() => setTab("contacts")}>Contacts</button></div><DataTable headers={[tab === "accounts" ? "Account" : "Contact", "Score", "Qualification", "Next action"]} loading={accounts.isLoading || leads.isLoading} empty="Upload a list from a campaign workspace to build this library.">{records?.map((record: any) => <tr key={record.id}><td><strong>{record.name || "Unnamed"}</strong><span>{record.domain || record.email || record.title || "Identity review required"}</span></td><td>{record.score}</td><td><Status value={record.qualification} /></td><td>{label(record.next_action)}</td></tr>)}</DataTable></section>; }

function Accounts({ workspaceId }: { workspaceId: string }) {
  const accounts = useQuery({ queryKey: ["accounts", workspaceId], queryFn: () => api.companies(workspaceId), refetchInterval: 5000 });
  const [message, setMessage] = useState(""); const [selectedId, setSelectedId] = useState<string | null>(null);
  const selected = accounts.data?.find((account) => account.id === selectedId); const qualification = accounts.data?.reduce((total, account) => ({ ...total, [account.qualification]: (total[account.qualification] || 0) + 1 }), {} as Record<string, number>) || {};
  const completedBriefs = accounts.data?.filter((account) => (account.enrichment_data?.ai_research as { status?: string } | undefined)?.status === "completed").length || 0;
  const research = async () => { try { const result = await api.queueAccountResearch(workspaceId); setMessage(result.queued ? `${result.queued} qualified accounts queued. Open an account’s evidence panel to follow its AI brief.` : completedBriefs ? `${completedBriefs} account briefs are already complete, so nothing new was queued. Select View evidence on any account to read its AI brief.` : "No account is currently eligible for AI research. The account threshold is 40; open an account’s evidence panel to review its score context and missing firmographic signals."); await accounts.refetch(); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Account research could not be queued"); } };
  return <section><PageHeader title="Accounts" description="Imported companies are scored from supplied firmographics, growth, funding, and data-quality signals." actions={<><button className="button-quiet" onClick={research}>Run AI research</button><Link className="button" to="/imports">Import accounts</Link></>} />{accounts.data?.length ? <div className="account-summary"><span><b>{qualification.qualified || 0}</b> qualified</span><span><b>{qualification.nurture || 0}</b> nurture</span><span><b>{qualification.unqualified || 0}</b> unqualified</span><span>AI research requires a score of <b>40+</b>.</span></div> : null}{message && <p className="notice">{message}</p>}<DataTable headers={["Company", "Profile", "Score", "Next action", "Evidence"]} loading={accounts.isLoading} empty="Import an accounts file to build your company directory.">{accounts.data?.map((account) => <tr key={account.id}><td><strong>{account.name || "Unnamed company"}</strong><span>{account.domain || "No domain"}</span></td><td>{account.industry || "Unclassified"}<span>{account.employee_band || "Size unknown"}</span></td><td><b>{account.score}</b> <Status value={account.qualification} /></td><td>{label(account.next_action)}</td><td><button className="button-quiet" onClick={() => setSelectedId(account.id)}>View evidence</button></td></tr>)}</DataTable>{selected && <AccountEvidence account={selected} onClose={() => setSelectedId(null)} />}</section>;
}

function AccountEvidence({ account, onClose }: { account: import("./api").Company; onClose: () => void }) {
  const dialogRef = useRef<HTMLElement>(null);
  const research = (account.enrichment_data?.ai_research || {}) as Record<string, unknown>; const output = (research.output || {}) as Record<string, unknown>; const profile = account.profile_data || {};
  const evidence = ["Industry", "Industry Tags", "Product and Services", "Description", "Company Country", "Headcount", "Total headcount growth (12 months)", "Total Funding", "Last Funding Type", "Last Funding Date"].filter((field) => profile[field]);
  const list = (value: unknown) => Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : [];
  useEffect(() => {
    const priorOverflow = document.body.style.overflow;
    const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); };
    document.body.style.overflow = "hidden";
    dialogRef.current?.focus();
    window.addEventListener("keydown", onKeyDown);
    return () => { document.body.style.overflow = priorOverflow; window.removeEventListener("keydown", onKeyDown); };
  }, [onClose]);
  return <div className="evidence-overlay" onMouseDown={onClose}><article className="evidence-dialog" aria-describedby="account-evidence-description" aria-labelledby="account-evidence-title" aria-modal="true" aria-live="polite" onMouseDown={(event) => event.stopPropagation()} ref={dialogRef} role="dialog" tabIndex={-1}><header><div><span className="section-label">Account evidence</span><h3 id="account-evidence-title">{account.name || account.domain || "Account"}</h3><p id="account-evidence-description">SignalFlow exposes the research brief as readable evidence, not raw model JSON.</p></div><button className="button-quiet" onClick={onClose}>Close</button></header><div className="evidence-meta"><Status value={String(research.status || "not_started")} /><span>Score {account.score}/100</span><span>Qualification threshold: 40</span>{Boolean(research.model) && <span>Model: {String(research.model)}</span>}{Boolean(research.prompt_version) && <span>Prompt: {String(research.prompt_version)}</span>}{Boolean(research.latency_ms) && <span>{String(research.latency_ms)} ms</span>}</div>{research.status === "completed" ? <div className="evidence-grid"><section><h4>Account brief</h4><p>{String(output.company_summary || "No summary returned.")}</p><h4>ICP assessment</h4><p>{String(output.icp_assessment || "No assessment returned.")}</p></section><section><h4>Why now</h4><EvidenceList items={list(output.why_now)} empty="No supported timing signals were found." /><h4>Personalization angles</h4><EvidenceList items={list(output.personalization_angles)} empty="No supported angles were found." /><h4>Recommended roles</h4><EvidenceList items={list(output.recommended_roles)} empty="No role categories were returned." /></section><section><h4>Data gaps</h4><EvidenceList items={list(output.data_gaps)} empty="No material data gaps were reported." /><h4>Suggested next action</h4><p>{String(output.suggested_next_action || account.next_action)}</p></section></div> : <div className="evidence-empty"><h4>{research.status === "blocked_ai_unavailable" ? "Local Ollama is unavailable" : account.qualification !== "qualified" ? "This account is not eligible for AI research yet" : "No account brief yet"}</h4><p>{research.error_message ? String(research.error_message) : account.qualification !== "qualified" ? "Add or correct industry, employee size, country, growth, funding, or product-context fields, then re-import or recalculate the account." : "Run AI research and follow the job in Jobs. The completed brief will appear here automatically."}</p></div>}<footer><h4>Imported evidence available to the model</h4>{evidence.length ? <div className="evidence-tags">{evidence.map((field) => <span key={field}>{field}</span>)}</div> : <p className="muted">No supported research fields were found in this account export.</p>}</footer></article></div>;
}
function EvidenceList({ items, empty }: { items: string[]; empty: string }) { return items.length ? <ul className="evidence-list">{items.map((item) => <li key={item}>{item}</li>)}</ul> : <p className="muted">{empty}</p>; }
function Leads({ workspaceId }: { workspaceId: string }) { const leads = useQuery({ queryKey: ["leads", workspaceId], queryFn: () => api.leads(workspaceId) }); return <section><PageHeader title="Leads" description="Qualified contacts and verified company inboxes ready for human-reviewed outreach." actions={<Link className="button" to="/imports">Import contacts</Link>} /><DataTable headers={["Contact", "Source", "Score", "Qualification", "Next action"]} loading={leads.isLoading} empty="Import contacts with Email and Company Domain to create leads.">{leads.data?.map((lead) => <tr key={lead.id}><td><strong>{lead.name || "Unnamed contact"}</strong><span>{lead.email || lead.title || "Identity review required"}</span></td><td>{label(lead.source)}</td><td><b>{lead.score}</b></td><td><Status value={lead.qualification} /></td><td>{label(lead.next_action)}</td></tr>)}</DataTable></section>; }
function Outreach({ workspaceId }: { workspaceId: string }) { const drafts = useQuery({ queryKey: ["outreach", workspaceId], queryFn: () => api.outreachDrafts(workspaceId) }); const replies = useQuery({ queryKey: ["replies", workspaceId], queryFn: () => api.replies(workspaceId), refetchInterval: 10000 }); const [message, setMessage] = useState(""); const review = async (id: string, status: "approved" | "rejected") => { await api.reviewOutreachDraft(id, workspaceId, status, status === "approved" ? "Approved for campaign use." : "Needs revision."); setMessage(`Draft ${status}.`); await drafts.refetch(); }; return <section><PageHeader title="Outreach inbox" description="Review evidence-bound Ollama drafts and triage Gmail replies without exposing message bodies in list views." />{message && <p className="notice">{message}</p>}<h3 className="section-label">Replies</h3><DataTable headers={["Subject", "Classification", "Received"]} loading={replies.isLoading} empty="No campaign replies have been synchronized yet.">{replies.data?.map((reply) => <tr key={reply.id}><td><strong>{reply.subject}</strong><span>Thread {reply.gmail_thread_id || "unavailable"}</span></td><td><Status value={reply.classification} /></td><td>{new Date(reply.received_at).toLocaleString()}</td></tr>)}</DataTable><h3 className="section-label">AI-generated drafts</h3><DataTable headers={["Recipient", "First message", "Status", "Review"]} loading={drafts.isLoading} empty="No drafts yet. Qualified contacts must complete Ollama analysis first.">{drafts.data?.map((draft) => <tr key={draft.id}><td><strong>{draft.lead_name || "Unnamed contact"}</strong><span>{draft.lead_email || "No email"}</span></td><td><strong>{draft.subject}</strong><span>{draft.sequence[0]?.body.slice(0, 110)}</span></td><td><Status value={draft.status} /></td><td>{draft.status === "draft" ? <div className="inline-actions"><button className="button-quiet" onClick={() => review(draft.id, "approved")}>Approve</button><button className="button-quiet danger" onClick={() => review(draft.id, "rejected")}>Reject</button></div> : "Reviewed"}</td></tr>)}</DataTable></section>; }
function Imports({ workspaceId }: { workspaceId: string }) { const [file, setFile] = useState<File | null>(null); const [kind, setKind] = useState<"accounts" | "leads">("accounts"); const [record, setRecord] = useState<{ filename: string; status: string; id: string; job?: { name: string } } | null>(null); const [error, setError] = useState(""); const upload = async (event: FormEvent) => { event.preventDefault(); if (!file) return setError("Choose a CSV or XLSX file."); try { setRecord(await api.createImport(workspaceId, file, kind)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Upload failed"); } }; const start = async () => { if (record) setRecord(await api.startImport(record.id, workspaceId)); }; return <section><PageHeader title="Imports" description="Validate data before workers create or join accounts and contacts. Imports are idempotent and recoverable." />{!record ? <form className="import-form" onSubmit={upload}><div className="segmented"><button type="button" className={kind === "accounts" ? "active" : ""} onClick={() => setKind("accounts")}>Accounts</button><button type="button" className={kind === "leads" ? "active" : ""} onClick={() => setKind("leads")}>Contacts</button></div><label>File<input type="file" accept=".csv,.xlsx" onChange={(event) => setFile(event.target.files?.[0] || null)} /></label><p>{kind === "accounts" ? "Company name, domain, headcount, industry, growth, funding, and country are supported." : "Email or full name plus company domain is required. Existing accounts enrich only missing values."}</p>{error && <p className="inline-error">{error}</p>}<button>Validate file</button></form> : <div className="panel import-result"><Status value={record.status} /><h3>{record.filename}</h3><p>{record.status === "validated" ? "Review the suggested mapping, then start the durable import job." : "Import state is persisted. Open Jobs to track live progress."}</p>{record.status === "validated" && <button onClick={start}>Start import</button>}{record.job && <p className="notice">{record.job.name} queued. Open Jobs for live progress.</p>}</div>}</section>; }
function Templates() { return <section><PageHeader title="Templates" description="Reusable message patterns remain grounded in approved campaign copy and local AI evidence." /><EmptyState title="Template library is ready for approved copy" body="Create and approve an outreach draft, then use it as the starting point for future campaign templates." /></section>; }
function Audit({ workspaceId }: { workspaceId: string }) { const audit = useQuery({ queryKey: ["audit", workspaceId], queryFn: () => api.audit(workspaceId) }); return <section><PageHeader title="Audit log" description="Immutable records of imports, decisions, delivery controls, and integration activity." />{audit.isLoading ? <Skeleton /> : <div className="audit-list">{audit.data?.map((item, index) => <article key={`${item.resource_id}-${index}`}><div><strong>{label(item.action)}</strong><p>{item.resource_type}: {item.resource_id}</p></div><time>{new Date(item.created_at).toLocaleString()}</time></article>)}</div>}</section>; }
function Settings({ workspaceId }: { workspaceId: string }) { const ollama = useQuery({ queryKey: ["ollama"], queryFn: api.ollama }); const suppressions = useQuery({ queryKey: ["suppressions", workspaceId], queryFn: () => api.suppressions(workspaceId) }); const [email, setEmail] = useState(""); const [reason, setReason] = useState("manual suppression"); const add = async (event: FormEvent) => { event.preventDefault(); await api.createSuppression(workspaceId, email, reason); setEmail(""); await suppressions.refetch(); }; return <section><PageHeader title="Settings" description="Advanced delivery, local AI, jobs, imports, and compliance controls." /><div className="overview-grid"><article className="panel"><h3>Required Ollama</h3><Status value={ollama.data?.ready ? "completed" : "blocked_ai_unavailable"} /><p>{ollama.data?.detail || "Checking local Ollama"}</p><p className="muted">Configured model: {ollama.data?.configured_model || "Not configured"}</p></article><article className="panel"><h3>Suppression list</h3><form onSubmit={add}><label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>Reason<input value={reason} onChange={(event) => setReason(event.target.value)} required /></label><button>Add suppression</button></form></article></div>{suppressions.data?.length ? <div className="resource-list">{suppressions.data.map((item) => <article className="resource-row" key={item.id}><strong>{item.email}</strong><span>{item.reason}</span></article>)}</div> : null}<details className="advanced-settings"><summary>Mailbox integrations</summary><IntegrationsView workspaceId={workspaceId} /></details><details className="advanced-settings"><summary>Processing jobs and diagnostics</summary><JobsView workspaceId={workspaceId} /></details><details className="advanced-settings"><summary>Audit history</summary><Audit workspaceId={workspaceId} /></details></section>; }
function DataTable({ headers, children, loading, empty }: { headers: string[]; children: ReactNode; loading: boolean; empty: string }) { const hasRows = Array.isArray(children) ? children.length > 0 : Boolean(children); return <div className="table-shell"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={headers.length}><Skeleton lines={3} /></td></tr> : hasRows ? children : <tr><td colSpan={headers.length}><EmptyState title="Nothing to show" body={empty} /></td></tr>}</tbody></table></div>; }
function Root() { const [session, setSession] = useState<Session | null>(null); const [loading, setLoading] = useState(true); useEffect(() => { restoreCsrfFromCookie(); api.session().then(setSession).catch(() => null).finally(() => setLoading(false)); }, []); if (loading) return <div className="app-loader"><Skeleton lines={4} /></div>; return <BrowserRouter basename="/app">{session ? <AppShell session={session} /> : <Login onSession={setSession} />}</BrowserRouter>; }
createRoot(document.getElementById("root")!).render(<QueryClientProvider client={client}><Root /></QueryClientProvider>);
