import { FormEvent, useEffect, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link, useNavigate, useParams } from "react-router-dom";
import { api, CampaignInput, CampaignSequenceBrief, CampaignStep, CampaignWorkspace as CampaignWorkspaceData } from "../../api";
import { EmptyState, PageHeader, Skeleton, Status, label } from "../../components/ui";

const defaults = [{ position: 1, delay_hours: 0, subject: "A quick question", body: "Hi,\n\nI am reaching out with a concise question based on the information available for your company. Would a short conversation be useful?", facts_used: ["Campaign brief"] }, { position: 2, delay_hours: 72, subject: "Following up", body: "Hi,\n\nI wanted to follow up on my earlier note. Is this a priority for your team right now?", facts_used: ["Prior outreach step"] }, { position: 3, delay_hours: 168, subject: "Closing the loop", body: "Hi,\n\nI will close the loop after this. If this becomes relevant, I would be glad to compare notes.", facts_used: ["Prior outreach step"] }];

export function CampaignsView({ workspaceId }: { workspaceId: string }) {
  const data = useQuery({ queryKey: ["campaigns", workspaceId], queryFn: () => api.campaigns(workspaceId) }); const navigate = useNavigate(); const [open, setOpen] = useState(false); const [error, setError] = useState("");
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const payload: CampaignInput = { workspace_id: workspaceId, name: String(form.get("name")), audience_filter: { campaign_first: true }, timezone: "UTC", business_hours: { start: 9, end: 17, weekdays: [0, 1, 2, 3, 4] }, daily_limit: 20, per_domain_limit: 1, steps: defaults }; try { const campaign = await api.createCampaign(payload); navigate(`/campaigns/${campaign.id}`); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not create campaign"); } };
  return <section><PageHeader title="Campaigns" description="A focused path from prepared prospects to a controlled launch." actions={<button onClick={() => setOpen(!open)}>Create campaign</button>} />{error && <p className="inline-error">{error}</p>}{open && <form className="campaign-builder" onSubmit={create}><label>Campaign name<input name="name" required autoFocus placeholder="Q4 operations outreach" /></label><p className="muted">Create the draft first. Upload and prepare the audience inside its workspace.</p><button>Create draft</button></form>}{data.isLoading ? <Skeleton /> : data.data?.length ? <div className="resource-list">{data.data.map((campaign) => <Link className="campaign-row campaign-link" key={campaign.id} to={`/campaigns/${campaign.id}`}><div><div className="campaign-title"><strong>{campaign.name}</strong><Status value={campaign.status} /></div><p>{campaign.enrollment_total} enrolled · {campaign.steps.length} messages · daily limit {campaign.daily_limit}</p></div><span>Open workspace →</span></Link>)}</div> : <EmptyState title="Start with a campaign" body="Create a draft, then upload accounts or contacts. SignalFlow prepares the audience automatically." action={<button onClick={() => setOpen(true)}>Create campaign</button>} />}</section>;
}

export function CampaignWorkspace({ workspaceId }: { workspaceId: string }) {
  const { campaignId = "" } = useParams(); const data = useQuery({ queryKey: ["campaign-workspace", campaignId, workspaceId], queryFn: () => api.campaignWorkspace(campaignId, workspaceId), enabled: Boolean(campaignId), refetchInterval: 4000 }); const [tab, setTab] = useState<"audience" | "sequence" | "launch" | "results">("audience"); const [message, setMessage] = useState("");
  if (data.isLoading) return <Skeleton lines={8} />; if (!data.data) return <EmptyState title="Campaign unavailable" body={data.error instanceof Error ? data.error.message : "Return to campaigns and choose a draft."} action={<Link to="/campaigns">Return to campaigns</Link>} />; const campaign = data.data;
  return <section><PageHeader title={campaign.name} description="Prepare the audience, review the sequence, test delivery, then launch." actions={<Link className="button-quiet" to="/campaigns">All campaigns</Link>} />{message && <p className="notice">{message}</p>}<div className="campaign-steps" role="tablist">{(["audience", "sequence", "launch", "results"] as const).map((item, index) => <button key={item} role="tab" aria-selected={tab === item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}><span>{index + 1}</span>{label(item)}</button>)}</div>{tab === "audience" && <Audience campaign={campaign} workspaceId={workspaceId} notice={setMessage} refresh={data.refetch} />}{tab === "sequence" && <Sequence campaign={campaign} workspaceId={workspaceId} notice={setMessage} refresh={data.refetch} />}{tab === "launch" && <Launch campaign={campaign} workspaceId={workspaceId} notice={setMessage} refresh={data.refetch} />}{tab === "results" && <Results campaign={campaign} />}</section>;
}

function Audience({ campaign, workspaceId, notice, refresh }: { campaign: CampaignWorkspaceData; workspaceId: string; notice: (s: string) => void; refresh: () => unknown }) {
  const [file, setFile] = useState<File | null>(null); const [kind, setKind] = useState<"auto" | "accounts" | "leads">("auto"); const [busy, setBusy] = useState(false); const summary = campaign.audience_summary;
  const upload = async (event: FormEvent) => { event.preventDefault(); if (!file) return notice("Choose a CSV or XLSX file first."); setBusy(true); try { const result = await api.importCampaignAudience(campaign.id, workspaceId, file, kind); notice(`${result.import.filename} is being prepared as ${result.detected_kind}.`); setFile(null); await refresh(); } catch (caught) { notice(caught instanceof Error ? caught.message : "Upload failed"); } finally { setBusy(false); } };
  const toggle = async (id: string, selected: boolean) => { try { await api.setCampaignAudienceMember(campaign.id, id, workspaceId, selected ? "exclude" : "include"); await refresh(); } catch (caught) { notice(caught instanceof Error ? caught.message : "Could not update prospect"); } };
  return <div className="workspace-section"><div className="pipeline-strip">{["Importing", "Enriching", "Scoring", "Researching", "Drafting", "Ready"].map((stage, index) => <div className={index < 3 || (!summary.researching && !summary.drafting && summary.ready) ? "complete" : summary.researching && stage === "Researching" ? "running" : ""} key={stage}><i>{index + 1}</i><span>{stage}</span></div>)}</div><form className="upload-bar" onSubmit={upload}><input type="file" accept=".csv,.xlsx" onChange={(event) => setFile(event.target.files?.[0] || null)} /><select value={kind} onChange={(event) => setKind(event.target.value as typeof kind)}><option value="auto">Auto-detect file</option><option value="accounts">Accounts only</option><option value="leads">Contacts</option></select><button disabled={busy}>{busy ? "Starting…" : "Upload & prepare"}</button></form><p className="muted">Company inboxes remain eligible with a shared-inbox warning; accounts without recipient email remain researchable only.</p><div className="signal-strip audience-counts">{["total", "ready", "researching", "missing_email", "suppressed"].map((key) => <div key={key}><strong>{summary[key] || 0}</strong><span>{label(key)}</span></div>)}</div>{campaign.imports[0] && <p className="notice">Latest import: {campaign.imports[0].filename} · {label(campaign.imports[0].status)}</p>}<div className="table-shell"><table><thead><tr><th>Prospect</th><th>Score</th><th>Preparation</th><th>Safeguard</th><th /></tr></thead><tbody>{campaign.audience.length ? campaign.audience.map((member) => <tr key={member.id}><td><strong>{member.name || "Company inbox"}</strong><span>{member.email || "No recipient email"}</span></td><td>{member.score ?? "—"}</td><td><Status value={member.readiness} /></td><td>{member.warning || member.exclusion_reason || "—"}</td><td><button className="button-quiet" onClick={() => toggle(member.id, member.selected)}>{member.selected ? "Exclude" : "Include"}</button></td></tr>) : <tr><td colSpan={5}><EmptyState title="Upload your first prospect list" body="Results stay scoped to this campaign." /></td></tr>}</tbody></table></div><button className="button-quiet" onClick={async () => { await api.prepareCampaign(campaign.id, workspaceId); notice("Retrying incomplete preparation."); await refresh(); }}>Retry preparation</button></div>;
}

function Sequence({ campaign, workspaceId, notice, refresh }: { campaign: CampaignWorkspaceData; workspaceId: string; notice: (s: string) => void; refresh: () => unknown }) {
  const saved = (campaign.audience_filter.campaign_brief || {}) as Partial<CampaignSequenceBrief>; const [brief, setBrief] = useState<CampaignSequenceBrief>({ workspace_id: workspaceId, goal: saved.goal || "Start relevant conversations", offer: saved.offer || "A concise review of the current workflow", target_persona: saved.target_persona || "Revenue operations leaders", cta: saved.cta || "Would a short conversation be useful?", proof: saved.proof || "", preset: saved.preset || "value_first" }); const [steps, setSteps] = useState<CampaignStep[]>(campaign.steps); useEffect(() => setSteps(campaign.steps), [campaign.steps]); const change = (key: keyof CampaignSequenceBrief, value: string) => setBrief((previous) => ({ ...previous, [key]: value })); const edit = (position: number, key: keyof CampaignStep, value: string | number) => setSteps((previous) => previous.map((step) => step.position === position ? { ...step, [key]: value } : step));
  const generate = async () => { try { const result = await api.generateCampaignSequence(campaign.id, brief); setSteps(result.steps); notice("Ollama generated an evidence-bound sequence. Review it before launch."); await refresh(); } catch (caught) { notice(caught instanceof Error ? caught.message : "Sequence generation failed"); } };
  const save = async () => { try { await api.updateCampaignSequence(campaign.id, { ...brief, steps: steps.map(({ id, ...step }) => step) }); notice("Sequence saved."); await refresh(); } catch (caught) { notice(caught instanceof Error ? caught.message : "Could not save sequence"); } };
  return <div className="workspace-section"><div className="sequence-brief"><label>Goal<textarea value={brief.goal} onChange={(e) => change("goal", e.target.value)} /></label><label>Offer<textarea value={brief.offer} onChange={(e) => change("offer", e.target.value)} /></label><label>Target persona<input value={brief.target_persona} onChange={(e) => change("target_persona", e.target.value)} /></label><label>CTA<input value={brief.cta} onChange={(e) => change("cta", e.target.value)} /></label><label>Verified proof only<textarea value={brief.proof} onChange={(e) => change("proof", e.target.value)} placeholder="Optional. Do not add claims you cannot verify." /></label><label>Writing preset<select value={brief.preset} onChange={(e) => change("preset", e.target.value)}><option value="value_first">Value-first</option><option value="problem_proof">Problem and proof</option><option value="short_direct">Short direct</option></select></label></div><div className="inline-actions"><button onClick={generate}>Generate with local Ollama</button><button className="button-quiet" onClick={save}>Save edits</button></div><div className="sequence-editor">{steps.map((step, index) => <article key={step.position}><header><strong>Email {index + 1}</strong><label>Delay (hours)<input type="number" min="0" value={step.delay_hours} onChange={(e) => edit(step.position, "delay_hours", Number(e.target.value))} /></label></header><label>Subject<input value={step.subject} onChange={(e) => edit(step.position, "subject", e.target.value)} /></label><label>Body<textarea value={step.body} onChange={(e) => edit(step.position, "body", e.target.value)} /></label><p className="muted">Evidence: {step.facts_used?.join(", ") || "Campaign brief only"}</p></article>)}</div></div>;
}

function Launch({ campaign, workspaceId, notice, refresh }: { campaign: CampaignWorkspaceData; workspaceId: string; notice: (s: string) => void; refresh: () => unknown }) {
  const integration = useQuery({ queryKey: ["gmail", workspaceId], queryFn: () => api.gmail(workspaceId) }); const [mailboxId, setMailboxId] = useState(campaign.mailbox_id || ""); const [daily, setDaily] = useState(campaign.daily_limit); const [domain, setDomain] = useState(campaign.per_domain_limit); const [testRecipient, setTestRecipient] = useState("");
  const save = async () => { try { await api.updateCampaignDelivery(campaign.id, { workspace_id: workspaceId, mailbox_id: mailboxId || undefined, timezone: campaign.timezone, business_hours: campaign.business_hours, daily_limit: Number(daily), per_domain_limit: Number(domain) }); notice("Delivery settings saved."); await refresh(); } catch (caught) { notice(caught instanceof Error ? caught.message : "Could not save delivery settings"); } };
  const action = async (name: "approve" | "test" | "activate") => { try { if (name === "approve") await api.campaignAction(campaign.id, workspaceId, "approve"); else if (name === "test") await api.testCampaign(campaign.id, workspaceId, testRecipient || undefined); else await api.activateCampaign(campaign.id, workspaceId); notice(name === "activate" ? "Campaign launched within configured safeguards." : `${label(name)} completed.`); await refresh(); } catch (caught) { notice(caught instanceof Error ? caught.message : "Campaign action failed"); } };
  return <div className="workspace-section"><div className="launch-grid"><article className="panel"><h3>Sending controls</h3><label>Mailbox<select value={mailboxId} onChange={(e) => setMailboxId(e.target.value)}><option value="">Choose a connected mailbox</option>{integration.data?.connections.filter((item) => item.status === "connected").map((item) => <option key={item.id} value={item.id}>{item.email} ({item.provider})</option>)}</select></label><label>Daily limit<input type="number" min="1" max="200" value={daily} onChange={(e) => setDaily(Number(e.target.value))} /></label><label>Per-domain limit<input type="number" min="1" max="5" value={domain} onChange={(e) => setDomain(Number(e.target.value))} /></label><button className="button-quiet" onClick={save}>Save sending controls</button><p className="muted">Connect SMTP/IMAP or optional Gmail OAuth in <Link to="/settings">Settings</Link>.</p></article><article className="panel"><h3>Launch checklist</h3>{campaign.readiness.blockers.length ? <ul className="checklist">{campaign.readiness.blockers.map((item) => <li key={item}>○ {item}</li>)}</ul> : <p className="success-copy">All launch gates have passed.</p>}<label>Test recipient<input type="email" value={testRecipient} onChange={(e) => setTestRecipient(e.target.value)} placeholder="Defaults to your sender mailbox" /></label><div className="inline-actions">{campaign.status === "draft" && <button onClick={() => action("approve")}>Approve campaign</button>}{campaign.status === "approved" && <button onClick={() => action("test")}>Send test email</button>}{campaign.status === "approved" && campaign.test_sent_at && <button onClick={() => action("activate")}>Launch campaign</button>}</div></article></div></div>;
}

function Results({ campaign }: { campaign: CampaignWorkspaceData }) { return <div className="workspace-section"><div className="signal-strip">{Object.entries({ ...campaign.results, remaining: Math.max(0, (campaign.audience_summary.ready || 0) - (campaign.results.sent || 0)) }).map(([key, value]) => <div key={key}><strong>{value}</strong><span>{label(key)}</span></div>)}</div><div className="panel"><h3>Campaign activity</h3>{campaign.activity.length ? campaign.activity.map((item, index) => <div className="compact-row" key={`${item.action}-${index}`}><div><strong>{label(item.action)}</strong><span>{new Date(item.created_at).toLocaleString()}</span></div></div>) : <EmptyState title="No activity yet" body="Preparation, review, test delivery, and sends will appear here." />}</div></div>; }
