import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { api } from "../../api";
import { EmptyState, PageHeader, Status } from "../../components/ui";

export function IntegrationsView({ workspaceId }: { workspaceId: string }) {
  const integration = useQuery({ queryKey: ["gmail", workspaceId], queryFn: () => api.gmail(workspaceId) }); const [message, setMessage] = useState("");
  const connect = async () => { try { const result = await api.connectGmail(workspaceId); window.location.assign(result.authorization_url); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not start Gmail connection"); } };
  const connectLocal = async () => { try { const result = await api.connectSmtpImap(workspaceId); setMessage(`SMTP/IMAP mailbox connected: ${result.mailbox.email}`); await integration.refetch(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not verify the SMTP/IMAP mailbox"); } };
  const sync = async (id: string) => { try { const result = await api.syncGmail(id, workspaceId); setMessage(`Gmail sync queued: ${result.job.name}`); await integration.refetch(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not queue Gmail sync"); } };
  const disconnect = async (id: string) => { if (!window.confirm("Disconnect this mailbox? Scheduled messages will not send until another connected mailbox is selected.")) return; await api.disconnectGmail(id, workspaceId); await integration.refetch(); };
  const useLocalMailbox = integration.data?.smtp_imap_configured;
  return <section><PageHeader title="Integrations" description="Connect a local SMTP/IMAP mailbox. Credentials remain encrypted server-side and are never exported." actions={<div className="row-actions"><button onClick={connectLocal} disabled={!useLocalMailbox}>Connect local mailbox</button>{!useLocalMailbox && <button className="button-quiet" onClick={connect} disabled={!integration.data?.configured}>Connect Gmail OAuth</button>}</div>} />{message && <p className="notice">{message}</p>}{!useLocalMailbox && <div className="setup-callout"><h3>Local mailbox setup is incomplete</h3><p>Add {integration.data?.smtp_imap_setup_required.join(", ")} to your local .env file, then restart API, worker, and scheduler services. This adapter sends with SMTP and synchronizes IMAP replies from a durable UID cursor.</p></div>}{integration.data?.connections.length ? <div className="resource-list">{integration.data.connections.map((mailbox) => <article className="resource-row" key={mailbox.id}><div><strong>{mailbox.email}</strong><p>{mailbox.provider === "smtp_imap" ? "SMTP send and IMAP reply sync" : "Gmail API"}. Last sync: {mailbox.last_sync_at ? new Date(mailbox.last_sync_at).toLocaleString() : "Not started"}</p>{mailbox.last_error && <p className="inline-error">{mailbox.last_error}</p>}</div><div className="row-actions"><Status value={mailbox.status} /><button className="button-quiet" onClick={() => sync(mailbox.id)}>Sync replies</button><button className="button-quiet danger" onClick={() => disconnect(mailbox.id)}>Disconnect</button></div></article>)}</div> : integration.isSuccess && <EmptyState title="No mailbox connected" body="Connect your local SMTP/IMAP mailbox, then send a campaign test before activation." />}</section>;
}
